name: CI

on:
  push:
    branches: [main]
    paths:
      - 'packages/**'
  pull_request:
    branches: [main]
    paths:
      - 'packages/**'

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --immutable

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: bun run lint

  build_and_test:
    name: Build and test
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build base packages
        # Only the base packages need to be built before testing
        run: bun run build:base
      - name: Test all packages
        run: bun run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
