name: Prettier

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Prettify code
        uses: creyD/prettier_action@v4
        with:
          dry: true
          # This must always match the `pretty-print` script in /package.json
          prettier_options: --check "*.{mj,t}s examples/**/*" "packages/*/src/**" "packages/*/dev/**" "packages/react-querybuilder/genericTests/**" "website/*.js" "website/{docs,src,versioned_docs,versioned_sidebars}/**"
          prettier_plugins: 'prettier-plugin-organize-imports'
      - name: Git diff
        if: ${{ failure() }}
        run: git diff && exit 1
